#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the ShardCoin network
 * @generated by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */

// ShardCoin: No hardcoded seeds yet. Add your own seed nodes here.
static const uint8_t chainparams_seed_main[] = {};
static const uint8_t chainparams_seed_test[] = {};

#endif // BITCOIN_CHAINPARAMSSEEDS_H
